name: poke_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  # Programación funcional
  dartz: ^0.10.1

  # Cliente HTTP
  dio: ^5.4.3+1

  flutter:
    sdk: flutter

  # Manejador de estado.
  flutter_bloc: ^8.1.6

  # Inyección de dependencias
  get_it: ^7.7.0

  # Base de datos local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
